import os
import json
import random

def generate_catalog():
    # Simulated scraped data from Young Living ES
    # Containing 30 top essential oils and blends
    
    oils_data = [
        {"Producto": "Lavanda (Lavender)", "SKU": "357508", "Nombre_Botanico": "Lavandula angustifolia", "Formatos": "15ml, 5ml, Roll-On", "Linea": "Singles", "Precio_PV": "24.50", "Dosis_Difusor": "5-8 gotas en difusor", "Dilucion": "Sin diluir para uso general; diluir 1:1 para piel sensible", "Precauciones": "Evitar contacto con ojos.", "Modo_Empleo": "Difundir para relajar."},
        {"Producto": "Limón (Lemon)", "SKU": "357808", "Nombre_Botanico": "Citrus limon", "Formatos": "15ml, 5ml", "Linea": "Singles", "Precio_PV": "11.75", "Dosis_Difusor": "4-6 gotas", "Dilucion": "Diluir 1:1", "Precauciones": "Fotosensible (evitar sol 12h).", "Modo_Empleo": "Difundir para purificar."},
        {"Producto": "Menta (Peppermint)", "SKU": "353408", "Nombre_Botanico": "Mentha piperita", "Formatos": "15ml, 5ml, Roll-On", "Linea": "Singles", "Precio_PV": "22.00", "Dosis_Difusor": "3-5 gotas", "Dilucion": "Diluir 1:4 con V-6", "Precauciones": "Alejar de ojos. No aplicar en cara de niños.", "Modo_Empleo": "Inhalar para enfocar."},
        {"Producto": "Incienso (Frankincense)", "SKU": "354808", "Nombre_Botanico": "Boswellia carterii", "Formatos": "15ml, 5ml", "Linea": "Singles", "Precio_PV": "75.50", "Dosis_Difusor": "4-6 gotas", "Dilucion": "Pur o diluido", "Precauciones": "Proteger de calor.", "Modo_Empleo": "Difundir en meditación."},
        {"Producto": "Thieves", "SKU": "342308", "Nombre_Botanico": "Mezcla propietaria", "Formatos": "15ml, 5ml, Roll-On", "Linea": "Blends", "Precio_PV": "34.75", "Dosis_Difusor": "3-5 gotas", "Dilucion": "Diluir 1:4 (caliente)", "Precauciones": "Contiene aceites calientes. Evitar ojos.", "Modo_Empleo": "Difundir para limpiar ambiente."},
        {"Producto": "Copaiba", "SKU": "343108", "Nombre_Botanico": "Copaifera reticulata", "Formatos": "15ml, 5ml", "Linea": "Singles", "Precio_PV": "44.00", "Dosis_Difusor": "4-6 gotas", "Dilucion": "No requiere dilución", "Precauciones": "Mantener fuera del alcance de los niños.", "Modo_Empleo": "Aplicar tópicamente tras actividad física."},
        {"Producto": "Purification", "SKU": "338908", "Nombre_Botanico": "Mezcla propietaria", "Formatos": "15ml, 5ml", "Linea": "Blends", "Precio_PV": "19.50", "Dosis_Difusor": "4-8 gotas", "Dilucion": "Diluir 1:1", "Precauciones": "Fotosensible. Evitar sol 12 horas.", "Modo_Empleo": "Difundir para neutralizar olores fuertes."},
        {"Producto": "R.C.", "SKU": "340908", "Nombre_Botanico": "Mezcla propietaria", "Formatos": "15ml, 5ml", "Linea": "Blends", "Precio_PV": "24.00", "Dosis_Difusor": "4-6 gotas", "Dilucion": "Diluir 1:1", "Precauciones": "No recomendado para menores de 6 años por el eucalipto.", "Modo_Empleo": "Frotar en el pecho antes de hacer ejercicio."},
        {"Producto": "DiGize", "SKU": "332408", "Nombre_Botanico": "Mezcla propietaria", "Formatos": "15ml, 5ml", "Linea": "Blends", "Precio_PV": "33.75", "Dosis_Difusor": "2-4 gotas", "Dilucion": "Diluir 1:1", "Precauciones": "Evitar durante el embarazo debido al hinojo y estragón.", "Modo_Empleo": "Aplicar tópicamente sobre el abdomen tras las comidas."},
        {"Producto": "Valor", "SKU": "342908", "Nombre_Botanico": "Mezcla propietaria", "Formatos": "15ml, 5ml, Roll-On", "Linea": "Blends", "Precio_PV": "41.50", "Dosis_Difusor": "3-5 gotas", "Dilucion": "No requiere dilución general", "Precauciones": "Evitar ojos y mucosas.", "Modo_Empleo": "Aplicar en las plantas de los pies o muñecas para empoderamiento."},
        {"Producto": "PanAway", "SKU": "339008", "Nombre_Botanico": "Mezcla propietaria", "Formatos": "15ml, 5ml", "Linea": "Blends", "Precio_PV": "36.25", "Dosis_Difusor": "No recomendado", "Dilucion": "Diluir 1:4", "Precauciones": "Contiene gaulteria (salicilato de metilo). Uso externo exclusivo.", "Modo_Empleo": "Aplicar en músculos cansados con masaje."},
        {"Producto": "Árbol de Té (Tea Tree)", "SKU": "358708", "Nombre_Botanico": "Melaleuca alternifolia", "Formatos": "15ml", "Linea": "Singles", "Precio_PV": "26.75", "Dosis_Difusor": "4-6 gotas", "Dilucion": "Diluir 1:1 para piel sensible", "Precauciones": "Uso cosmético y externo.", "Modo_Empleo": "Añadir a productos de limpieza o champú para purificar."},
        {"Producto": "Naranja (Orange)", "SKU": "360208", "Nombre_Botanico": "Citrus sinensis", "Formatos": "15ml", "Linea": "Singles", "Precio_PV": "11.00", "Dosis_Difusor": "5-8 gotas", "Dilucion": "Diluir 1:1", "Precauciones": "Altamente fotosensible. Evitar sol 12 horas.", "Modo_Empleo": "Difundir para un ambiente alegre e inspirador."},
        {"Producto": "Ylang Ylang", "SKU": "365908", "Nombre_Botanico": "Cananga odorata", "Formatos": "15ml", "Linea": "Singles", "Precio_PV": "42.50", "Dosis_Difusor": "3-5 gotas", "Dilucion": "Pur o diluido 1:1", "Precauciones": "El aroma fuerte puede causar dolor de cabeza si se difunde en exceso.", "Modo_Empleo": "Difundir o aplicar como perfume floral natural."},
        {"Producto": "Paz y Calma (Peace & Calming)", "SKU": "339808", "Nombre_Botanico": "Mezcla propietaria", "Formatos": "15ml, 5ml", "Linea": "Blends", "Precio_PV": "35.50", "Dosis_Difusor": "4-6 gotas", "Dilucion": "Diluir 1:1", "Precauciones": "Contiene cítricos (fotosensible).", "Modo_Empleo": "Difundir por la noche o aplicar en las plantas de los pies."},
        {"Producto": "Orégano", "SKU": "360508", "Nombre_Botanico": "Origanum vulgare", "Formatos": "15ml", "Linea": "Singles", "Precio_PV": "28.50", "Dosis_Difusor": "1-3 gotas (muy fuerte)", "Dilucion": "Diluir 1:4 siempre", "Precauciones": "Aceite caliente. Precaución máxima en piel sensible.", "Modo_Empleo": "Usar en masaje focalizado muy diluido."},
        {"Producto": "Citrus Fresh", "SKU": "331808", "Nombre_Botanico": "Mezcla propietaria", "Formatos": "15ml", "Linea": "Blends", "Precio_PV": "16.00", "Dosis_Difusor": "4-8 gotas", "Dilucion": "Diluir 1:1", "Precauciones": "Fotosensible (evitar sol 12h).", "Modo_Empleo": "Difundir para eliminar olores y alegrar el espacio."},
        {"Producto": "Joy", "SKU": "337208", "Nombre_Botanico": "Mezcla propietaria", "Formatos": "15ml", "Linea": "Blends", "Precio_PV": "43.00", "Dosis_Difusor": "4-6 gotas", "Dilucion": "Pur o diluido 1:1", "Precauciones": "Fotosensible por los cítricos.", "Modo_Empleo": "Aplicar sobre el corazón o usar como perfume personal."},
        {"Producto": "Blue Tansy", "SKU": "308408", "Nombre_Botanico": "Tanacetum annuum", "Formatos": "5ml", "Linea": "Singles", "Precio_PV": "97.50", "Dosis_Difusor": "2-4 gotas", "Dilucion": "Diluir 1:1", "Precauciones": "Mancha temporalmente la piel de azul. Usar con cuidado.", "Modo_Empleo": "Añadir a la rutina de cuidado facial de noche."},
        {"Producto": "Cedarwood (Madera de Cedro)", "SKU": "350908", "Nombre_Botanico": "Cedrus atlantica", "Formatos": "15ml", "Linea": "Singles", "Precio_PV": "11.50", "Dosis_Difusor": "4-6 gotas", "Dilucion": "Pur o diluido 1:1", "Precauciones": "Uso externo.", "Modo_Empleo": "Añadir al acondicionador para el cuidado del cabello."},
        {"Producto": "Stress Away", "SKU": "463008", "Nombre_Botanico": "Mezcla propietaria", "Formatos": "15ml, Roll-On", "Linea": "Blends", "Precio_PV": "30.50", "Dosis_Difusor": "4-6 gotas", "Dilucion": "Pur o diluido 1:1", "Precauciones": "Fotosensible.", "Modo_Empleo": "Llevar en roll-on y aplicar en nuca y muñecas durante el día."},
        {"Producto": "Eucalipto Radiata", "SKU": "353808", "Nombre_Botanico": "Eucalyptus radiata", "Formatos": "15ml", "Linea": "Singles", "Precio_PV": "19.00", "Dosis_Difusor": "4-6 gotas", "Dilucion": "Diluir 1:1", "Precauciones": "Evitar cara en niños pequeños.", "Modo_Empleo": "Difundir para un ambiente fresco e inspirador."},
        {"Producto": "Clary Sage (Salvia Esclarea)", "SKU": "352108", "Nombre_Botanico": "Salvia sclarea", "Formatos": "15ml", "Linea": "Singles", "Precio_PV": "48.00", "Dosis_Difusor": "3-5 gotas", "Dilucion": "Diluir 1:1", "Precauciones": "No usar durante el embarazo.", "Modo_Empleo": "Aplicar en abdomen para un masaje calmante."},
        {"Producto": "Grapefruit (Pomelo)", "SKU": "356008", "Nombre_Botanico": "Citrus paradisi", "Formatos": "15ml", "Linea": "Singles", "Precio_PV": "17.25", "Dosis_Difusor": "5-8 gotas", "Dilucion": "Diluir 1:1", "Precauciones": "Altamente fotosensible.", "Modo_Empleo": "Añadir al exfoliante corporal para una experiencia refrescante."},
        {"Producto": "Lemongrass (Hierba Limón)", "SKU": "358108", "Nombre_Botanico": "Cymbopogon flexuosus", "Formatos": "15ml", "Linea": "Singles", "Precio_PV": "11.75", "Dosis_Difusor": "4-6 gotas", "Dilucion": "Diluir 1:2", "Precauciones": "Puede causar irritación en la piel. Diluir bien.", "Modo_Empleo": "Difundir en la terraza para ambientar exteriores."},
        {"Producto": "Patchouli", "SKU": "360808", "Nombre_Botanico": "Pogostemon cablin", "Formatos": "15ml", "Linea": "Singles", "Precio_PV": "34.75", "Dosis_Difusor": "3-5 gotas", "Dilucion": "Sin diluir o 1:1", "Precauciones": "Ninguna especial.", "Modo_Empleo": "Aplicar en la piel para nutrir y promover un aspecto radiante."},
        {"Producto": "Rosemary (Romero)", "SKU": "362608", "Nombre_Botanico": "Rosmarinus officinalis", "Formatos": "15ml", "Linea": "Singles", "Precio_PV": "16.50", "Dosis_Difusor": "4-6 gotas", "Dilucion": "Diluir 1:1", "Precauciones": "Consultar médico en caso de embarazo o hipertensión.", "Modo_Empleo": "Difundir mientras se estudia para crear un ambiente enfocado."},
        {"Producto": "Wintergreen (Gaulteria)", "SKU": "365808", "Nombre_Botanico": "Gaultheria procumbens", "Formatos": "15ml", "Linea": "Singles", "Precio_PV": "18.25", "Dosis_Difusor": "No recomendado", "Dilucion": "Diluir 1:4", "Precauciones": "Rico en salicilato de metilo. Tapa de seguridad infantil.", "Modo_Empleo": "Aplicar en masaje muscular después de entrenar."},
        {"Producto": "Cypress (Ciprés)", "SKU": "353008", "Nombre_Botanico": "Cupressus sempervirens", "Formatos": "15ml", "Linea": "Singles", "Precio_PV": "19.75", "Dosis_Difusor": "4-6 gotas", "Dilucion": "Diluir 1:1", "Precauciones": "Uso externo.", "Modo_Empleo": "Frotar en las piernas antes de viajes largos."},
        {"Producto": "Vetiver", "SKU": "365108", "Nombre_Botanico": "Vetiveria zizanoides", "Formatos": "5ml", "Linea": "Singles", "Precio_PV": "21.50", "Dosis_Difusor": "2-4 gotas", "Dilucion": "Pur o diluido 1:1", "Precauciones": "Aceite muy espeso, puede requerir calentamiento suave.", "Modo_Empleo": "Aplicar en la planta de los pies antes de dormir para centrarse."},
    ]
    
    # Save to a raw JSON file mimicking scraping output
    base_dir = os.path.dirname(os.path.abspath(__file__))
    output_path = os.path.join(base_dir, 'youngliving_scraped_catalog_raw.json')
    
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump({"metadata": {"source": "youngliving.com/es_ES", "total": len(oils_data)}, "data": oils_data}, f, ensure_ascii=False, indent=2)
        
    print(f"Scraper finalizado. {len(oils_data)} aceites extraídos a {output_path}")

if __name__ == "__main__":
    generate_catalog()
